version: "3"

services:

  mo_ldap_events:
    build: .
    command: "poetry run python -m mo_ldap_events.ldap_agent next-events-to-queue"
    environment:
      amqp_url: amqp://guest:guest@msg_broker
    volumes:
      - ./mo_ldap_events:/opt/app/
    networks:
      - os2mo_default

networks:
  os2mo_default:
    external: true
